general:
  name: "structured_hadamard_marchenko_padded128"
  recon: "spec"
  save: True

signal:
  shape: [1,1,128,128]
  mode: ["unit","shepp-logan"]
  config:


model:
  spectrum: "unit"
  n_layers: 2
  diagonal:
    # left one is closer to the input
    mode: [['marchenko','uniform'],['unit','uniform']] # mag: 'unit', 'marchenko', phase: 'uniform', 'laplace', 'quadrant'
    config:
      #degree_of_freedom: 30
      #radius: 0.8
  transform: "hadamard" # 'fft', 'dct', 'hadamard'
  pad_powers_of_two: True
  shared_weights: False

recon:
  series: "arange"
  start: 2
  end: 258
  list: []
  n_repeats: 50
  max_iter: 5000

save:
  path: "../runs"
  name: "res_{model_name}_{structure}_{img_mode[0]}_{img_mode[1]}_{recon}.csv"