general:
  name: "fdf_random_2pi"
  recon: "spec"
  save: True
  verbose: False

signal:
  shape: [1,1,64,64]
  mode: ["unit","random"] #["delta","constant"]
  config:
    n_layers: 0

model:
  spectrum:
    mode: "unit"
    product: 1
  n_layers: 1.5
  diagonals:
    #! left one is closer to the input
    mode: [['marchenko','uniform']] # mag: 'unit', 'marchenko', phase: 'uniform', 'laplace', 'quadrant'
    config:
      #degree_of_freedom: 30
      #radius: 0.8
  transforms: ["fourier2","fourier2"] # 'fourier', 'cosine', 'hadamard' + dimension
  pad_powers_of_two: False
  shared_weights: False

recon:
  series: "arange"
  start: 2
  end: 194
  list: []
  n_repeats: 50
  max_iter: 5000

save:
  path: "../runs"
  name: "{model_name}_{structure}_{recon}.csv"