general:
  name: "structured_hadamard"
  recon: "spec"
  save: True

signal:
  img_size: 64
  mode: "shepp-logan"
  config:
    noise_ratio: 0.0 # noise ratio for mix mode
    unit_mag: True
    max_scale: 40.0 # max scale for varying magnitude

model:
  n_layers: 2
  diagonal:
    mode: [['unit','uniform'],['unit','uniform']] # mag: 'unit', 'marchenko', phase: 'uniform', 'laplace', 'quadrant'
    config:
      placeholder: 0 # use when no config
      #degree_of_freedom: 30
      #radius: 0.8
  transform: "hadamard" # 'fft', 'dct', 'hadamard'
  shared_weights: False

recon:
  series: "arange"
  start: 80
  end: 120
  list: []
  n_repeats: 10
  max_iter: 5000

save:
  path: "../runs"
  name: "res_{model_name}_{structure}_{img_mode}_{recon}.csv"