general:
  name: "full-unitary"
  recon: "gd_spec"
  save: True
  verbose: False

signal:
  shape: [1,1,64,64]
  mode: ["unit","shepp-logan"] #["delta","constant"]
  config:
    n_layers: 0

model:
  mode: "unitary" # null, "unitary", "circulant"
  unit_mag: False
  product: 1

recon:
  series: "arange"
  start: 1.0
  end: 9.1
  step: 0.1
  list: []
  n_repeats: 50
  max_spec_iter: 5000
  gd:
    loss: 'intensity'
    prior: 'zero'
    early_stop: True
    max_iter: 10000
    spectrum: 'unitary'

save:
  path: "../runs"
  name: "{model_name}_{recon}.csv"