general:
  name: "structured_marchenko_uniform_phase"
  recon: "spec"
  save: True

signal:
  img_size: 64
  mode: "shepp-logan"
  config:
    noise_ratio: 0.0 # noise ratio for mix mode
    unit_mag: True
    max_scale: 40.0 # max scale for varying mag

model:
  n_layers: 2
  diagonal:
    mode: ['uniform_phase', 'triangular'] # 'uniform_phase', 'gaussian', 'laplace', 'marchenko', 'student-t', 'uniform', 'triangular'
    config:
      degree_of_freedom: 30
      complex: False
      unit_mag: True
  transform: "fft"
  shared_weights: False

recon:
  series: "arange"
  start: 70
  end: 194
  list: []
  n_repeats: 50
  max_iter: 5000

save:
  path: "../runs"
  name: "res_{model_name}_{structure}_{img_mode}_{recon}_{oversampling_start}-{oversampling_end}_{n_repeats}repeat.csv"